apiVersion: networking.istio.io/v1beta1
kind: WorkloadEntry
metadata:
  name: helloworld-vm
  namespace: helloworld-ns
  annotations:
    sidecar-bootstrap.istio.io/ssh-user: istio-proxy
    sidecar-bootstrap.istio.io/proxy-config-dir: /etc/istio-proxy
    sidecar-bootstrap.istio.io/proxy-image-hub: docker.io/tetrate
    sidecar-bootstrap.istio.io/proxy-instance-ip: 10.0.101.189
spec:
  address: 18.116.69.249
  labels:
    class: vm
    app: helloworld
    version: v2
  serviceAccount: default
  network: aws
